AM.UI.Web/Models/ErrorViewModel.cs
namespace AM.UI.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AM.UI.Web/Models/WebExtensions.cs
namespace AM.UI.Web.Models
{
    public static class WebExtensions
    {
        public static string AddRequestFile(this HttpRequest httpRequest, IWebHostEnvironment webHostEnvironment, params string[] paths)
        {
            if (httpRequest.Form.Files.Count > 0)
            {
                var allPaths = new string[paths.Length + 2];

                allPaths[0] = webHostEnvironment.ContentRootPath;
                paths.CopyTo(allPaths, 1);

                var file = httpRequest.Form.Files[0];
                allPaths[^1] = file.FileName;

                using (var stream = new FileStream(Path.Combine(allPaths), FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                return file.FileName;
            }

            return null;
        }
    }
}

AM.UI.Web/Controllers/FlightController.cs
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using AM.ApplicationCore.Services;
using AM.UI.Web.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AM.UI.Web.Controllers
{
    public class FlightController : Controller
    {
        IUnitOfWork unitOfWork;
        IFlightService flightService;
        IWebHostEnvironment webHostEnvironment;
        IPlaneService planeService;
        public FlightController(IUnitOfWork unitOfWork, IFlightService flightService, IWebHostEnvironment webHostEnvironment, IPlaneService planeService)
        {
            this.unitOfWork = unitOfWork;
            this.flightService = flightService;
            this.webHostEnvironment = webHostEnvironment;
            this.planeService = planeService;
        }
        // GET: FlightController
        public ActionResult Index()
        {
            return View(flightService.GetAll());
        }

        [HttpPost]
        public ActionResult Index(DateTime? flightDate)
        {
            return View(flightDate == null ? flightService.GetAll() : flightService.GetFlightsGreaterThan(flightDate.Value));
        }

        // GET: FlightController/Details/5
        public ActionResult Details(int id)
        {
            return View(flightService.GetById(id));
        }

        // GET: FlightController/Create
        public ActionResult Create()
        {
            ViewBag.Planes = new SelectList(planeService.GetAll().Select(e => new {e.PlaneId, Description=$"PlaneId : {e.PlaneId}, Capacity = {e.Capacity}"}), nameof(Plane.PlaneId), "Description"); 
            return View();
        }

        // POST: FlightController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Flight flight)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                var fileName = Request.AddRequestFile(webHostEnvironment, "wwwroot", "upload");

                flight.Pilot = fileName;
                flightService.Add(flight);
                unitOfWork.Commit();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(flightService.GetById(id));
        }

        // POST: FlightController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Flight flight)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                flightService.Update(flight);
                unitOfWork.Commit();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(flightService.GetById(id));
        }

        // POST: FlightController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Flight flight)
        {
            try
            {
                flight.FlightId = id;
                flightService.Delete(flight);
                unitOfWork.Commit();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.Web/Controllers/HomeController.cs
using AM.UI.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AM.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AM.UI.Web/Controllers/PlaneController.cs
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using AM.ApplicationCore.Services;
using AM.UI.Web.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AM.UI.Web.Controllers
{
    public class PlaneController : Controller
    {
        IUnitOfWork unitOfWork;
        IPlaneService planeService;
        public PlaneController(IUnitOfWork unitOfWork, IPlaneService planeService)
        {
            this.unitOfWork = unitOfWork;
            this.planeService = planeService;
        }
        // GET: PlaneController
        public ActionResult Index()
        {
            return View(planeService.GetAll());
        }

        // GET: PlaneController/Details/5
        public ActionResult Details(int id)
        {
            return View(planeService.GetById(id));
        }

        // GET: PlaneController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlaneController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Plane plane)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                planeService.Add(plane);
                unitOfWork.Commit();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PlaneController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PlaneController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.Web/Views/Flight/Create.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Departure" class="control-label"></label>
                <input asp-for="Departure" class="form-control" />
                <span asp-validation-for="Departure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveArrival" class="control-label"></label>
                <input asp-for="EffectiveArrival" class="form-control" />
                <span asp-validation-for="EffectiveArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDuration" class="control-label"></label>
                <input asp-for="EstimatedDuration" class="form-control" />
                <span asp-validation-for="EstimatedDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightDate" class="control-label"></label>
                <input asp-for="FlightDate" class="form-control" />
                <span asp-validation-for="FlightDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightId" class="control-label"></label>
                <input asp-for="FlightId" class="form-control" />
                <span asp-validation-for="FlightId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneId" class="control-label"></label>
                <select asp-for="PlaneId" class="form-control" asp-items="ViewBag.Planes">
                    <option>Select plane</option>
                </select>
                <span asp-validation-for="PlaneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot" class="control-label"></label>
                <input asp-for="Pilot" class="form-control" type="file" name="pilotImageFile" />
                <span asp-validation-for="Pilot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Flight/Delete.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffectiveArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffectiveArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AM.UI.Web/Views/Flight/Details.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffectiveArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffectiveArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneId)
        </dd>
        <dd style="background-color:orange">
            <partial name="~/Views/Plane/Details.cshtml" model="Model.Plane" />
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FlightId }) |
    <a asp-action="Index">Back to List</a>
</div>

AM.UI.Web/Views/Flight/Edit.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Departure" class="control-label"></label>
                <input asp-for="Departure" class="form-control" />
                <span asp-validation-for="Departure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveArrival" class="control-label"></label>
                <input asp-for="EffectiveArrival" class="form-control" />
                <span asp-validation-for="EffectiveArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDuration" class="control-label"></label>
                <input asp-for="EstimatedDuration" class="form-control" />
                <span asp-validation-for="EstimatedDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightDate" class="control-label"></label>
                <input asp-for="FlightDate" class="form-control" />
                <span asp-validation-for="FlightDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightId" class="control-label"></label>
                <input asp-for="FlightId" class="form-control" />
                <span asp-validation-for="FlightId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneId" class="control-label"></label>
                <input asp-for="PlaneId" class="form-control" />
                <span asp-validation-for="PlaneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Flight/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Flight>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-action="Index">
    Search by Flight Date :
    <input type="date" name="flightDate" />
    <input type="submit" value="Serach" />
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="Index" asp-controller="Plane">Liste des avions</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EffectiveArrival)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedDuration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Plane.PlaneType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilot)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Departure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EffectiveArrival)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneId)
            </td>
            <td>
                @if(item.Plane != null)
                {
                    <a asp-action="Details" asp-controller="Plane" asp-route-id="@item.Plane.PlaneId">@item.Plane.PlaneType</a>
                }
            </td>
            <td>
                <img src="@Url.Content("~/upload/" + item.Pilot)"                
                  style="display:@(string.IsNullOrEmpty(item.Pilot) ? "none": null)" />
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.FlightId }) |
                @Html.ActionLink("Details", "Details", new { id=item.FlightId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.FlightId })
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AM.UI.Web/Views/Plane/Create.cshtml
@using AM.ApplicationCore.Domain
@model AM.ApplicationCore.Domain.Plane

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Plane</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufactureDate" class="control-label"></label>
                <input asp-for="ManufactureDate" class="form-control" />
                <span asp-validation-for="ManufactureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneId" class="control-label"></label>
                <input asp-for="PlaneId" class="form-control" />
                <span asp-validation-for="PlaneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneType" class="control-label"></label>
                <select asp-for="PlaneType" class="form-control" asp-items="Html.GetEnumSelectList<PlaneType>()">
                    <option>Select type</option>
                </select>
                <span asp-validation-for="PlaneType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Plane/Details.cshtml
@model AM.ApplicationCore.Domain.Plane

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufactureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneType)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AM.UI.Web/Views/Plane/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Plane>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufactureDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Capacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufactureDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneType)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AM.UI.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AM.UI.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AM.UI.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="Index">Fligths</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AM.UI.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>